### ISSUE TITLE
[Q] Is it possible to get rid of unnecessary `Maybe` in generated types?

### ISSUE THREAD

**Issue by ablearthy** [mejgun/haskell-tdlib#6]
Hi! It's really good to see that we have a library for building Telegram clients in Haskell.
I have the question: is it possible to get rid of unnecessary `Maybe` in generated types?

For example, every field in [`BotInfo`](https://haskell-tdlib.netlify.app/td-data-botinfo) is `Maybe`. As I know, it's safe to remove `Maybe`s from fields whose description doesn't [contain](https://github.com/tdlib/td/blob/cb164927417f22811c74cd8678ed4a5ab7cb80ba/td/generate/TlDocumentationGenerator.php#L284) `may be null`.

**Comment by ablearthy** [comment]
Also `BotInfo.description` doesn't have a documentation string. That's because in [tl file](https://github.com/tdlib/td/blob/cb164927417f22811c74cd8678ed4a5ab7cb80ba/td/generate/scheme/td_api.tl#L1022) it's annotated as `@param_description`

**Comment by mejgun** [comment]
Thank you, and sorry for the delayed response.

I tried to do this at first, but I don’t think we can fully rely on handwritten documentation. It may contain vague descriptions like 'pass null if'. Wrongly added or removed clarifications may cause runtime errors.

**Comment by mejgun** [comment]
> Also `BotInfo.description` doesn't have a documentation string. That's because in [tl file](https://github.com/tdlib/td/blob/cb164927417f22811c74cd8678ed4a5ab7cb80ba/td/generate/scheme/td_api.tl#L1022) it's annotated as `@param_description`

Thanks for pointing this out!
